# The URL the site will be built for
base_url = "https://www.raultaveras.online"
theme = "linkita" # NB: This was implemented as a git submodule, not cloned.

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Raúl E. Taveras's Website"
generate_feeds = true
feed_filenames = ["atom.xml"]


# When set to "true", the generated HTML files are minified.
minify_html = true
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 4

[extra]
# Put all your custom variables here
header_menu_name = "menu_name"

[extra.profiles.raul]
name = "Raúl Ernesto Taveras Franco"
bio = "I am Raúl: Christian, linguistics lover, diplomacy professional, citizen of the world. Welcome to my website!"
avatar_url = "raulforward1.jpg"
avatar_alt = "Raul facing toward the camera, wearing a black hoodie"

[extra.menus]
menu_name = [
  { url = "$BASE_URL/articles/", name = "Articles" },
  { url = "$BASE_URL/tags/", name = "Tags" },
]


# Use relative urls.
# It doesn't apply for content yet.
# Default value: false
relative_urls = true

# If you want to view the site without a webserver
# set this and "relative_urls" to true.
# Default value: false
urls_to_index_html = true

[extra.footer]
license_url = "https://creativecommons.org/licenses/by/4.0/"
copyright = "&copy; $YEAR Raúl Ernesto Taveras Franco &vert; [CC BY 4.0]($LICENSE_URL)"
