---
title: "Podcasts I Listen To"
draft: false
---

For reference, I currently use the Android app [[https://www.bing.com/ck/a?!&&p=67e6787c20fb56b3JmltdHM9MTY5Nzc2MDAwMCZpZ3VpZD0wMTAwYTY0NC01MmFkLTZhYWYtM2U3NC1iNWMwNTNkNjZiNjUmaW5zaWQ9NTIyNg&ptn=3&ver=2&hsh=3&fclid=0100a644-52ad-6aaf-3e74-b5c053d66b65&psq=podcast+addict+play+store&u=a1aHR0cHM6Ly9wbGF5Lmdvb2dsZS5jb20vc3RvcmUvYXBwcy9kZXRhaWxzP2lkPWNvbS5iYW1idW5hLnBvZGNhc3RhZGRpY3Q&ntb=1][Podcast Addict]] to listen to podcasts.

** Linguistics and Language
- A Way with Words
- Conlangery – For Constructing Languages
- Lexicon Valley
- New Books in Language
- That's What They Say
- The Allusionist
- The Endless Knot
- Words for Granted
- Wordy Wordpecker
- [[https://historyofenglishpodcast.com/][The History of English]]
- [[https://lingthusiasm.com/][Lingthusiasm]]
- en clair: forensic linguistics, literary detection, language mysteries, and more

** History
- The History of Rome Podcast - The OG History Podcast.
- The History of Bizantium Podcast - A Successor to the History of Rome.
- The Revolutions Podcast - A podcast about world revolutions by the same guy who made The History of Rome.
- Footnoting History
- The History of the Papacy Podcast
- The History of China
- The History of Islam
- Dan Carlin's Hardcore History
- Stuff You Missed in History Class
- Wrath of the Khans Series by Dan Carlin

** Design
- 99% Invisible - The Best on Design in all senses: Urban, space, interior, graphic, transit, systems, sound, and whatever else you can think of. Probably more.

** General Knowledge
- Tell Me Something I Don't Know
- Freakonomics: A podcast about economics and related things (hint: everything) by brilliant economist and communicator Stephen Dubner. This podcast is for everyone who wants to build a better society.
- Freakonomics MD: A spin-off of Freakonomics focusing on medical issues.
- Every Little Thing
- Stuff You Should Know
- Surprisingly Awesome
- The Neurospace Podcast - Made by my very knowledgable and passionate neurologist/psychologist friend, Camila Hasbún.
- El Brifin: Pocast Edition
- Extremities
- People I (Mostly) Admire
- Sudhir Breaks the Internet
- Inner Cosmos with David Eagleman — An excellent psychology and neurology podcast.

** Mathematics
- The Numberphile Podcast
- My Favorite Theorem

** Christian Sermons
- John Piper's Sermons (Desiring God)
- Renewing Your Mind with R.C. Sproul
- Renova2 - Made by my two dear and extremely talented friends Laura and Jason.
- Exploring my Strange Bible

** Bible Study and Theology
- [[https://bibleproject.com/podcasts/the-bible-project-podcast/][BibleProject Podcast]]
- [[https://onscript.study/][OnScript]]
- [[https://podcasts.apple.com/us/podcast/working-for-the-word-a-bible-translation-podcast/id1494281053][Working for the Word]]

** Fiction
- Among the Stars and Bones
- bomBARDed - A Musical Dungeons and Dragons Podcast
- Passenger List
- Girl in Space - My favorite fictional podcast.
- Spout Lore - A Dungeon World Podcast
- The Adventure Zone - An entertainment empire that started with Dungeons and Dragons
